### ISSUE TITLE
Indentation of UL/LI

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2016#77] opened 2016-08-24 09:31 UTC
![pasted image at 2016_08_24 11_21 am](https://cloud.githubusercontent.com/assets/283441/17925695/468c0588-69ee-11e6-847b-26825fed9a69.png)

**Comment by tricoder42** [comment] 2016-08-24 09:45
That's feature, not a bug :)

Bullets are moved "outside", so the text starts in the same column as paragraphs.

See:
http://webdesign.tutsplus.com/articles/getting-the-hang-of-hanging-punctuation--cms-19890
https://prowebtype.com/seeing-typographic-details/#hangingbullets
https://en.wikipedia.org/wiki/Hanging_punctuation

**Comment by tricoder42** [comment] 2016-08-24 11:57
If you really want to revert the default behavior, feel free to send PR. For now I'm closing this.

**Closed as completed by tricoder42** 2016-08-24 11:57 UTC
Labels: wontfix
